# Generated by Django 5.1.7 on 2025-03-31 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                ("amount", models.FloatField()),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("S", "Store_shopping"),
                            ("C", "CardToCard"),
                            ("Ch", "Charge"),
                            ("O", "Online_shopping"),
                        ],
                        default="C",
                        max_length=50,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Account_Transaction",
                        to="home.account",
                    ),
                ),
            ],
        ),
    ]
