# Generated by Django 5.1.7 on 2025-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
