# Generated by Django 5.1.7 on 2025-04-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_account_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseProfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profit percentage (e.g., 5 for 5%)",
                        max_digits=5,
                    ),
                ),
                ("duration", models.PositiveIntegerField(help_text="Duration in days")),
            ],
        ),
        migrations.RemoveField(
            model_name="profit",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="profit",
            name="title",
        ),
        migrations.AlterField(
            model_name="profit",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profit",
            name="base_profit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.baseprofit",
            ),
        ),
    ]
