# Generated by Django 5.1.7 on 2025-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_baseprofit_remove_profit_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profit",
            name="base_profit",
        ),
        migrations.AddField(
            model_name="profit",
            name="profit_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annually", "Annually")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="BaseProfit",
        ),
    ]
